# =============================================================================
#  metadata/layout.conf - overlay overlay-prismos-work
#  repo   : prismos-work
#  masters: portage-stable chromiumos eclass-overlay prismos-common
# =============================================================================
masters = portage-stable chromiumos eclass-overlay prismos-common
profile-formats = portage-2 profile-binpkg-compression
thin-manifests = false
manifest-hashes = SHA256 SHA512
sign-manifests = false
auto-sync = no
cache-format = md5-dict
