# Variabili comuni per tutti i profili prismOS
DISTRO_NAME="prismOS"
DISTRO_VERSION="0.1.0"
ISO_PUBLISHER="prismOS Project"
ISO_APPLICATION="prismOS Live System"
DEFAULT_LOCALE="it_IT.UTF-8"
DEFAULT_TIMEZONE="Europe/Rome"
DEFAULT_KEYBOARD="it"

BASE_PACKAGES="\
linux-firmware \
networkmanager \
sudo \
pipewire \
flatpak \
"
