PROFILE_ID="edu"
DISPLAY_NAME="prismOS EDU"
BASE_DESKTOP="plasma"
KERNEL_FLAVOR="generic"
TARGET_HARDWARE="school-lab"

PACKAGES="\
libreoffice \
firefox-esr \
geogebra \
stellarium \
moodle-desktop\
"

SERVICES_ENABLE="ssh"
SERVICES_DISABLE="bluetooth"
TUNING="cpu-governor=powersave;session-mode=restricted"
POLICY_FILE="profiles/edu.policy.json"
