PROFILE_ID="edu"
DISPLAY_NAME="prismOS EDU"
EDITION_DESCRIPTION="Ambiente scolastico con policy centralizzata e restrizioni configurabili."
BASE_DESKTOP="plasma"
DISPLAY_MANAGER="sddm"
KERNEL_FLAVOR="generic"
TARGET_HARDWARE="school-lab"

PACKAGES="\
libreoffice \
firefox-esr \
geogebra \
stellarium \
moodle-desktop \
kolibri\
"

SERVICES_ENABLE="ssh NetworkManager"
SERVICES_DISABLE="bluetooth"
TUNING="cpu-governor=powersave;session-mode=restricted;guest-session=disabled"
POLICY_FILE="profiles/edu.policy.json"
