PROFILE_ID="games"
DISPLAY_NAME="prismOS Games"
BASE_DESKTOP="plasma"
KERNEL_FLAVOR="zen"
TARGET_HARDWARE="gaming-desktop"

PACKAGES="\
steam \
lutris \
heroic-games-launcher \
gamemode \
mangohud \
pipewire\
"

SERVICES_ENABLE="bluetooth"
SERVICES_DISABLE="cups"
TUNING="cpu-governor=performance;gpu-mode=high"
