PROFILE_ID="games"
DISPLAY_NAME="prismOS Games"
EDITION_DESCRIPTION="Ottimizzata per gaming Linux, driver e bassa latenza."
BASE_DESKTOP="plasma"
DISPLAY_MANAGER="sddm"
KERNEL_FLAVOR="zen"
TARGET_HARDWARE="gaming-desktop"

PACKAGES="\
steam \
lutris \
heroic-games-launcher \
gamemode \
mangohud \
protonup-qt \
obs-studio \
pipewire\
"

SERVICES_ENABLE="bluetooth NetworkManager"
SERVICES_DISABLE="cups"
TUNING="cpu-governor=performance;gpu-mode=high;vm.max_map_count=2147483642"
