PROFILE_ID="slim"
DISPLAY_NAME="prismOS Slim"
BASE_DESKTOP="xfce"
KERNEL_FLAVOR="lts"
TARGET_HARDWARE="legacy-computers"

PACKAGES="\
mousepad \
abiword \
gnumeric \
firefox-esr \
htop\
"

SERVICES_ENABLE=""
SERVICES_DISABLE="bluetooth cups"
TUNING="cpu-governor=ondemand;zram=enabled;animations=off"
