PROFILE_ID="slim"
DISPLAY_NAME="prismOS Slim"
EDITION_DESCRIPTION="Edizione leggera per PC datati con RAM/CPU limitata."
BASE_DESKTOP="xfce"
DISPLAY_MANAGER="lightdm"
KERNEL_FLAVOR="lts"
TARGET_HARDWARE="legacy-computers"

PACKAGES="\
mousepad \
abiword \
gnumeric \
firefox-esr \
htop \
pcmanfm \
lxappearance\
"

SERVICES_ENABLE="NetworkManager"
SERVICES_DISABLE="bluetooth cups"
TUNING="cpu-governor=ondemand;zram=enabled;animations=off;swappiness=10"
