PROFILE_ID="work"
DISPLAY_NAME="prismOS Work"
BASE_DESKTOP="plasma"
KERNEL_FLAVOR="lowlatency"
TARGET_HARDWARE="modern-laptop-desktop"

PACKAGES="\
libreoffice \
firefox \
thunderbird \
code \
git \
docker \
network-manager-openvpn\
"

SERVICES_ENABLE="ssh docker"
SERVICES_DISABLE="bluetooth"
TUNING="cpu-governor=schedutil;io-scheduler=mq-deadline"
