PROFILE_ID="work"
DISPLAY_NAME="prismOS Work"
EDITION_DESCRIPTION="Ottimizzata per produttivita, sviluppo e collaborazione."
BASE_DESKTOP="plasma"
DISPLAY_MANAGER="sddm"
KERNEL_FLAVOR="lowlatency"
TARGET_HARDWARE="modern-laptop-desktop"

PACKAGES="\
libreoffice \
firefox \
thunderbird \
code \
git \
docker \
network-manager-openvpn \
nextcloud-client\
"

SERVICES_ENABLE="ssh docker NetworkManager"
SERVICES_DISABLE="bluetooth"
TUNING="cpu-governor=schedutil;io-scheduler=mq-deadline;swappiness=20"
